@url = http://localhost:3000/api/v1

GET http://localhost:3000/ HTTP/1.1
###
# @name getAll
GET {{url}}/stickers HTTP/1.1
###
# @name error
GET {{url}}/stickers/bad HTTP/1.1
###
# @name getById
GET {{url}}/stickers/1 HTTP/1.1
###
# @name getByIdNotExists
GET {{url}}/stickers/12 HTTP/1.1
###
# @name create
POST {{url}}/stickers HTTP/1.1
Content-Type: application/json

{
    "Title": "Git",
    "Description": "Git Logo",
    "Rating": 10,
    "URL": "http://devstickers.com/assets/img/pro/4mh6.png"
}
###
# @name update
PUT {{url}}/stickers/9 HTTP/1.1
Content-Type: application/json

{
    "Title": "Update",
    "Description": "Update Logo",
    "Rating": 3,
    "URL": "http://devstickers.com/assets/img/pro/4mh6.png"
}
###
# @name delete
DELETE {{url}}/stickers/10 HTTP/1.1
Content-Type: application/json

{
    "Id": 10
}