version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment: 
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    volumes:
      - app:/usr/src/app/node_modules
      - .:/usr/src/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - backend
    volumes:
      - app:/usr/src/app/node_modules
      - .:/usr/src/app
    command: ['yarn', 'test']

  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  app:
  db:

networks:
  frontend:
  backend:
