version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment: 
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_TEST_URL: ${DATABASE_TEST_URL}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - packages:/usr/src/app/node_modules
      - packages
    depends_on: 
      - db
      
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  packages:

networks:
  frontend:
  backend:
