version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment: 
      DATABASE_URL:
      DATABASE_TEST_URL:
      POSTGRES_USER:
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
    depends_on: 
      - db
      
  db:
    image: postgres:10
    environment:
      POSTGRES_DB:
    ports:
      - 5432:5432
    networks:
      - backend
      
networks:
  frontend:
  backend:
