version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
    depends_on:
      - db

  db:
    image: postgres:10
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  frontend:
  backend:
