version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_TEST_URL: ${DATABASE_TEST_URL}
      POSTGRES_USER: ${POSTGRES_USER}

  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
