version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["sh", "relay.sh", "db", "yarn", "dev"]
    environment:
      DATABASE_DEV_URL: ${DATABASE_DEV_URL}
      DATABASE_TEST_URL: ${DATABASE_TEST_URL}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - .:/usr/src/app
      - packages:/usr/src/app/node_modules
      - packages

  db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  packages:
